BoltzExchange/boltz-web-app

src/Nav.jsx, src/components/ApiOffline.jsx, src/css/index.css, src/css/nav.css, src/i18n/i18n.js, src/index.jsx
Closes https://github.com/BoltzExchange/boltz-web-app/issues/154
=> redo banner

src/components/SwapList.jsx
Closes https://github.com/BoltzExchange/boltz-web-app/issues/148
=> latest swap on top of past swap list

src/Refund.jsx, src/components/SwapList.jsx
=> fixup reverse signal if its null

src/css/asset.css, src/css/index.css
i think it nicer without the box for small devices!
=> optimize smartphone

src/configs/config.mainnet.js
=> use onion URLs when accessed via hidden service

src/css/hero.css
Closes https://github.com/BoltzExchange/boltz-web-app/issues/178
=> add padding to nodestats

src/css/index.css, src/i18n/i18n.js, src/status/InvoiceSet.jsx
=> make expected amount clearer

src/css/hero.css, src/css/index.css, src/css/nav.css
=> optimize swap box on mobile

src/i18n/i18n.js, src/status/SwapCreated.jsx
closes #189 
Important: Return to this page after paying invoice
or
Important: Return to this page after paying this invoice
=> add warning to claim the swap

src/Refund.jsx, src/helper.js, src/i18n/i18n.js, src/status/SwapExpired.jsx
https://github.com/BoltzExchange/boltz-web-app/assets/1743657/25d7c867-c876-4507-96cd-83f28cdfba8e
closes #206
closes #207
closes #205
=> refactor: improve refund file flow

src/css/hero.css, src/css/index.css
=> refactor: show full size swap box on landing page

src/NotFound.jsx, src/i18n/i18n.js, src/index.jsx
closes #221
redirect all not found routes to ```/404```
=> feat: add 404 page

src/components/AssetSelect.jsx
close asset dialog when clicking outside
=> FEAT: close choose asset dialog

src/components/SwapList.jsx
Proper date sorting for swap inside SwapList
=> fix: sort swap history by creation date

src/components/Fees.jsx
=> FEAT: remove fee reload icon

src/signals.js
=> FEAT: different referals for mobile and desktop

src/Pay.jsx, src/components/Asset.jsx, src/components/AssetSelect.jsx, src/components/BlockExplorer.jsx, src/components/Fees.jsx, src/configs/config.mainnet.js, src/configs/config.regtest.js, src/configs/config.testnet.js, src/helper.js, src/signals.js, src/style/index.scss, tests/components/BlockExplorer.spec.jsx, tests/configs/configs.spec.js, tests/utils/calculate.spec.js
this prs changing up our config.js and makes it possible to have a api_url on a per asset basis.
=> FEAT: Make APIs urls configurable per asset

src/History.jsx, src/Refund.jsx, src/components/DownloadRefund.jsx, src/i18n/i18n.js, src/utils/download.js, tests/History.spec.js
closes #150
you can now download a json of your local storage, and import it into another browser/session
should this feature be available for mobile? i think you cannot download json for iphone right? @michael1011 @armurbalda 
https://github.com/BoltzExchange/boltz-web-app/assets/1743657/0cb4ed6e-6891-4763-bdfa-b9e2223dbc62
=> FEAT: download history backup and restore

package-lock.json, package.json, src/Pay.jsx, src/helper.js, src/index.jsx, src/status/SwapCreated.jsx, src/utils/swapChecker.js, src/utils/swapStatus.js, tests/utils/swapChecker.spec.js
=> feat: multiple SSE swap update streams

src/Create.jsx
=> [FEAT] send amount stays the same if changing direction or asset or fees

src/Create.jsx, src/style/index.scss, tests/components/Create.spec.jsx
=> [FEAT] do not assume an amount

src/utils/validation.js, tests/utils/validation.spec.js
=> fix: validation of native SegWit normal Swap

src/helper.js
the if failed when swap() is set to null onCleanup()
Closes https://github.com/BoltzExchange/boltz-web-app/issues/256
=> fix: issue claiming in background

src/status/SwapCreated.jsx
=> feat: add cropped invoice and amount on rev swap screen

src/helper.js
=> fix: extra check if swap was already claimed

.git-commit-template.txt
Adding git commit template from https://github.com/BoltzExchange/boltz-backend/blob/master/.git-commit-template.txt
=> chore: add commit template

src/signals.js
=> fix: default swap direction

src/Nav.jsx, src/style/index.scss
=> fix: no # on language selector

src/Create.jsx
closes #252
https://github.com/BoltzExchange/boltz-web-app/assets/1743657/5524c008-4353-40a2-87c4-7e442c4d2755
=> feat: use invoice amount from pasted invoice

src/Create.jsx
=> fix: invoice validation #279, #277

src/Create.jsx, src/helper.js, src/utils/feeChecker.js, tests/utils/feeChecker.spec.js
=> fix: check fee amount instead of pair hash

src/Create.jsx, src/components/Fees.jsx, src/signals.js, tests/components/Create.spec.jsx
=> feat: change last changed send/receive amount on fee change

src/Pay.jsx, src/helper.js
=> fix: only claim from inside swapchecker

src/signals.js, tests/signals.spec.js
=> feat: save selected asset send/receive into localstorage

src/Create.jsx
https://github.com/BoltzExchange/boltz-web-app/assets/1743657/878349ef-1fc9-4943-b971-4ebd84ef8596
=> bug: decimals handling for 0.000

src/Create.jsx, src/components/ClickableAmount.jsx, src/style/index.scss, tests/components/ClickableAmount.spec.jsx, tests/components/Create.spec.jsx
=> feat: make min and max clickable

src/style/index.scss
=> fix: fixes scrollbar jump when clicking into swapbox

src/style/history.scss
=> feat: alignment past swaps

src/History.jsx, src/Pay.jsx, src/components/SwapList.jsx, src/style/history.scss, src/style/swaplist.scss
=> hotfix: alignment past swaps

src/Hero.jsx, src/Nav.jsx, src/signals.js, src/style/hero.scss, src/style/index.scss
closes #255
not sure if this is a good solution, but the only one i can think of, because routing from `/` to `/swap` always rerenders the Create component, thus loosing the state where you clicked.
=> feat: use swapbox on `/`

.pre-commit-config.yaml, src/i18n/index.js, src/index.jsx, src/signals.js, tests/utils/swapChecker.spec.js
also gets rid of annoying erros when running `vitest`
=> bug: out of context execution for effects/memo

src/Create.jsx
=> bug: missing space in Create

src/Create.jsx, src/Hero.jsx, src/Nav.jsx, src/configs/templates/defaults.js, src/helper.js, src/signals.js, src/style/nav.scss
=> chore: clean up, move signals into components

src/Create.jsx, src/style/index.scss
save some space make it neater
=> chore: optimize hr css

src/components/CreateButton.tsx, src/utils/invoice.ts
make button active again after fetching failure
=> fix: lnurl failure does not enable button again

src/components/ConnectMetamask.tsx, src/context/Web3.tsx, src/i18n/i18n.ts
=> fix: metamask not installed

src/status/InvoiceSet.jsx
=> fix: only show expiry warning for mainchain

src/components/CreateButton.tsx
Closes https://github.com/BoltzExchange/boltz-web-app/issues/370
also check if defined before extracting
=> fix: only set onchain addr on reverse swap

src/Create.jsx, src/components/AddressInput.tsx, src/components/ConnectMetamask.tsx, src/components/CreateButton.tsx, src/components/InvoiceInput.tsx, src/helper.js, src/utils/invoice.ts, src/utils/validation.ts, tests/utils/validation.spec.ts
=> fix: translate create button label on change

package-lock.json, package.json, src/components/AssetSelect.jsx, src/consts.ts, src/context/Web3.tsx, src/i18n/i18n.ts
now asset select will actually use assets configured on config.js
also closes https://github.com/BoltzExchange/boltz-web-app/issues/344
=> fix: assets depends on config settings

src/Create.jsx
closes https://github.com/BoltzExchange/boltz-web-app/issues/389
=> fix: revalidate amounts when address is valid

src/components/DownloadRefund.jsx, src/components/DownloadRefund.tsx
PS. we need the typescript refactor. download qr was not working
=> bugfix: missing qrcode import

src/Pay.jsx
fixed annoying issue on Create getting out of sync
=> fix: do not setReverse in Pay.jsx

src/components/Fees.jsx, src/style/index.scss
make a more obvious active state
closes: https://github.com/BoltzExchange/boltz-web-app/issues/390
=> feat: slightly nicer denominaction btn

src/style/nav.scss
small css fix. was not vertically centered.
=> fix: network button margin

package-lock.json, package.json, src/Create.jsx, src/components/AddressInput.tsx, src/components/QrScan.tsx, src/i18n/i18n.ts, src/signals.js, src/style/qrscan.scss, tests/components/AddressInput.spec.tsx, tests/components/QrScan.spec.tsx, vite.config.js
Closes https://github.com/BoltzExchange/boltz-web-app/issues/300
qrcode scanner :)
- BREAKING: camera needs https to be working so i added mkcert plugin for vite, works great but from now on we need `https://localhost:5173/`
=> feat: add qrscanner for addresses and invoices

src/Footer.jsx, src/configs/templates/defaults.ts, src/i18n/i18n.ts, src/style/footer.scss, vite.config.js
=> feat: add version footer

src/components/SwapList.tsx, src/style/swaplist.scss, tests/components/SwapList.spec.tsx
align the swaplist in history and refundable swap
=> feat: swaplist alignment

src/RefundStep.jsx, src/components/DownloadRefund.tsx, src/style/index.scss
=> feat: make btns width 100%

src/Pay.tsx, src/compat.ts, src/helper.ts, src/signals.ts
=> chore: move helper to ts

src/utils/invoice.ts, tests/utils/validation.spec.ts
=> fix: millisats precision broke validator

src/pages/Create.tsx
which entering a valid invoice and switching to another page and back, refs thrown a undefined error and app breaks
=> fix: issue create ref undefined

src/components/CreateButton.tsx, src/pages/Hero.tsx, src/pages/Pay.tsx, src/pages/Refund.tsx, src/status/SwapExpired.tsx, src/utils/helper.ts, src/utils/swapChecker.ts, tests/utils/swapChecker.spec.ts
dont use signal in fetcher, pass it instead
=> refactor: fetcher no signal

src/components/CreateButton.tsx, src/utils/feeChecker.ts, src/utils/helper.ts, tests/utils/feeChecker.spec.ts
remove asset signal and pass it
=> refactor: feeChecker no signals

src/components/SwapChecker.tsx, src/index.tsx, src/utils/helper.ts, tests/components/SwapChecker.spec.tsx
removes some createRoot weirdness and makes tests also easier
=> refactor: SwapChecker into component

src/status/InvoiceSet.tsx
=> fix: copy btc amount

src/components/CreateButton.tsx, src/utils/helper.ts
move feeCheck from helper to CreateButton components, its only used there
=> refactor: feeCheck move from helper

src/components/DownloadRefund.tsx, src/components/Refund.tsx, src/components/SwapChecker.tsx, src/context/Pay.tsx, src/index.tsx, src/pages/Pay.tsx, src/pages/RefundStep.tsx, src/signals.ts, src/status/InvoiceFailedToPay.tsx, src/status/InvoiceSet.tsx, src/status/SwapCreated.tsx, src/status/SwapExpired.tsx, src/status/SwapRefunded.tsx, src/status/TransactionConfirmed.tsx, src/status/TransactionLockupFailed.tsx, src/utils/helper.ts, tests/components/SwapChecker.spec.tsx
defer swapchecker when `refactor-swapchecker` and `refactor-feecheck` is merged.
=> refactor: use pay context for signals

src/pages/Create.tsx
switches to sat denom of amount > x
closes https://github.com/BoltzExchange/boltz-web-app/issues/391
=> feat: automatic denom switcher

src/pages/Create.tsx, src/style/index.scss
This reverts commit 0c770c04aaef52624f1f61b28c92671d0719a927.
=> refactor: revert to 0 as placeholder for amounts

src/components/SwapChecker.tsx, src/i18n/i18n.ts, src/pages/Pay.tsx, src/status/TransactionClaimPending.tsx, src/utils/boltzClient.ts, src/utils/claim.ts, src/utils/swapStatus.ts
Depends on https://github.com/BoltzExchange/boltz-backend/pull/478
=> feat: cooperative submarine claims

src/components/AddressInput.tsx
=> bug: address was not validated after assets switch

src/utils/invoice.ts, src/utils/validation.ts, tests/utils/invoice.spec.ts
=> fix: catch error on 0 amount invoices

src/components/SwapChecker.tsx
ran into this issue with some bad localstorage data. just an additional sanity check.
=> bug: safety check if swap was not found

src/components/Footer.tsx, src/configs/templates/defaults.ts, src/i18n/i18n.ts, src/style/footer.scss
=> feat: add testnet link

.git-commit-template.txt, package-lock.json, package.json, src/components/RefundButton.tsx, src/context/Global.tsx, src/pages/Refund.tsx, tests/components/RefundButton.spec.tsx, tests/pages/Refund.spec.tsx
closes #469
- dont use global signal for `refundTx`
=> feat: only show refund button when file is uploaded

src/components/AddressInput.tsx, src/components/ConnectMetamask.tsx, src/components/CreateButton.tsx, src/components/InvoiceInput.tsx, src/context/Create.tsx, src/pages/Create.tsx, src/types.ts
- introduce a types.ts for all the types
- move buttonLabel signal to context
=> refactor: introduce types.ts and move signals to contexts

src/index.tsx
did not work for 2 level deep links
=> bug: register serviceworker on `/`

src/index.tsx, tests/setup.ts
else we have a lot of console logs
=> test: set loglevel to error on tests

src/config.ts
We only have content from external producers really, I'm curating it in this playlist so I'd want to link directly to it
=> chore: change youtube link to playlist

src/style/nav.scss
=> bug: css issue on external link in menu

src/components/Footer.tsx, src/config.ts, src/i18n/i18n.ts
=> feat: add canary link

src/components/CreateButton.tsx, src/i18n/i18n.ts
=> feat: immediate create swap on lnaddress / lnurl

src/status/SwapCreated.tsx
=> feat: show return to page only on mobile

src/components/CreateButton.tsx, src/components/Fees.tsx, src/context/Global.tsx, src/pages/Create.tsx, src/pages/Hero.tsx, src/status/InvoiceSet.tsx, src/status/SwapCreated.tsx, src/utils/denomination.ts, src/utils/validation.ts, tests/pages/Create.spec.tsx, tests/utils/denomination.spec.ts
=> feat: add localized float separator

src/utils/invoice.ts, tests/utils/invoice.spec.ts
did not work button was enabled
=> fix: regtest invoice validation on mainnet

src/components/QrCode.tsx, src/status/InvoiceSet.tsx, src/style/asset.scss, src/style/qrcode.scss, src/style/vars.scss
=> feat: show qr code icon depending on invoice/onchain asset

README.md, src/config.ts
Avoids this annoying full screen subscription prompt
=> chore: blog link update

src/components/AssetSelect.tsx, src/components/Denomination.tsx, src/components/Fees.tsx, src/components/QrScan.tsx, src/components/Separator.tsx, src/components/SettingsCog.tsx, src/components/SettingsMenu.tsx, src/components/Tooltip.tsx, src/context/Global.tsx, src/i18n/i18n.ts, src/pages/Create.tsx, src/pages/History.tsx, src/pages/Pay.tsx, src/pages/Refund.tsx, src/style/index.scss, src/style/qrscan.scss, src/style/settings.scss, src/style/tooltip.scss, tests/pages/Refund.spec.tsx
adding settings menu, with denomination and decimal separator, in the future will have more like, 0conf, feerate, etc.
=> feat: add setting menu

src/context/Global.tsx
skipping refresh of globalcontext fixes issue: context is undefined
=> fix: hot reload issue

LICENSE
Needs ACK from all other major contributors @dni @michael1011 @armurbalda @jackstar12
Also we had 1 commit from @thelmuxkriovar and @otech47 each, so if you get too it, we'd appreciate your ACK too :pray:
=> feat: change license to AGPL3

src/i18n/i18n.ts, src/pages/Refund.tsx
=> chore: wording refund found in history

release.sh
Closes #561 
`sh release.sh v1.x.x`
=> feat: add `release.sh` for release chores

src/components/Tooltip.tsx
So that the message can be read on mobile
=> chore: increase tooltip click delay

src/i18n/i18n.ts, src/status/TransactionClaimed.tsx
=> feat: wording successful swap and show amount received

src/components/Logs.tsx, src/i18n/i18n.ts, src/style/index.scss, src/style/settings.scss
and ask if you are sure to delete
=> fix: log settings bigger buttons

src/consts/SwapStatus.ts, src/pages/Pay.tsx
Closes https://github.com/BoltzExchange/boltz-web-app/issues/622
=> fix: missing refund page for failed chain swap

docs/README.md
Else it looks like you have to install Node.js and npm to do a Docker build
=> chore: reorder run from source instructions

src/components/AssetSelect.tsx, tests/components/AssetSelect.spec.tsx
=> fix: swap box clears address on asset switch

src/pages/Create.tsx
=> fix: prevent pasting same value twice

CHANGELOG.md, package-lock.json, package.json
chore: bump version to v1.4.1 and prepare release
=> chore: update version to v1.4.1 and prepare release

package-lock.json, package.json, src/components/SwapList.tsx, src/index.tsx, src/pages/History.tsx, src/pages/Refund.tsx, src/style/index.scss, src/style/swaplist.scss, tests/pages/Refund.spec.tsx
closes #609 
more room for mobile, remove buttons for simplicity
=> feat: improve on `SwapList`

e2e/chainSwaps/chainSwaps.spec.ts, e2e/chainSwaps/overpayment.spec.ts, e2e/utils.ts, src/context/Global.tsx, src/i18n/i18n.ts, src/pages/RefundEvm.tsx, src/status/TransactionLockupFailed.tsx, src/utils/boltzClient.ts, tests/pages/Create.spec.tsx
Closes #629
Depends on https://github.com/BoltzExchange/boltz-backend/pull/657
=> feat: renegotiate chain swap amounts

docs/urlParams.md, src/context/Global.tsx, src/i18n/detect.ts, tests/i18n/detect.spec.ts
=> feat: language URL search parameter

src/components/CreateButton.tsx, src/i18n/i18n.ts
Closes #703
@kilrau check translations and if it fixes the issue on the weird mobile connection
=> fix: add timeout to BIP-353 DNS lookup

src/components/CreateButton.tsx
=> chore: bump bolt12 resolve timeout

src/components/ConnectWallet.tsx, src/pages/Create.tsx
=> feat: disable EVM connect button for invalid pairs

e2e/submarineSwap.spec.ts, e2e/utils.ts, src/i18n/i18n.ts, src/status/TransactionClaimed.tsx, src/utils/boltzClient.ts, src/utils/invoice.ts, src/utils/swapCreator.ts, tests/status/TransactionClaimed.spec.tsx, tests/utils/invoice.spec.ts
Closes #732 
Depends on https://github.com/BoltzExchange/boltz-backend/pull/720
@kilrau needs translations
=> feat: Submarine Swap preimage copy button

src/components/ConnectWallet.tsx, src/components/Warning.tsx, src/i18n/i18n.ts, src/pages/Error.tsx, src/pages/RefundStep.tsx, src/style/web3.scss
Closes #738
@kilrau needs translations
=> feat: show when no browser wallet found

e2e/chainSwaps/zeroAmount.spec.ts, src/components/AddressInput.tsx, src/components/CreateButton.tsx, src/components/PayInvoice.tsx, src/components/PayOnchain.tsx, src/i18n/i18n.ts, src/pages/Create.tsx, src/pages/Hero.tsx, src/pages/Pay.tsx, src/status/InvoiceSet.tsx, src/status/SwapCreated.tsx, src/status/TransactionLockupFailed.tsx, src/style/index.scss, src/utils/boltzClient.ts, src/utils/compat.ts, src/utils/denomination.ts, src/utils/helper.ts, src/utils/swapCreator.ts, src/utils/validation.ts, tests/components/PayOnchain.spec.tsx, tests/status/TransactionLockupFailed.spec.tsx, tests/utils/denomination.spec.ts, tests/utils/validation.spec.ts
Closes #719
@kilrau needs translations
=> feat: 0-amount chain swaps

src/status/TransactionLockupFailed.tsx
Only failed on testnet and regtest, so no need to rush out a hotfix release
=> fix: address parsing for new quote

src/components/HardwareDerivationPaths.tsx, src/style/web3.scss, src/utils/hardware/HadwareSigner.ts, src/utils/hardware/LedgerSigner.ts, src/utils/hardware/TrezorSigner.ts, src/utils/strings.ts
Closes #737
https://github.com/user-attachments/assets/0ebeb314-9375-404b-ace9-ddd28b51665c
=> feat: nicer HWW derivation path selection

src/components/SwapChecker.tsx, src/utils/boltzClient.ts, src/utils/claim.ts
Depends on https://github.com/BoltzExchange/boltz-backend/pull/743
=> feat: help server claim Chain Swaps that receive on EVM

e2e/locale.spec.ts, src/context/Global.tsx, src/i18n/detect.ts, src/pages/Create.tsx
=> fix: default browser language detection

e2e/fees.spec.ts, e2e/utils.ts, src/components/Fees.tsx, src/i18n/i18n.ts, src/utils/boltzClient.ts, src/utils/denomination.ts, tests/utils/denomination.spec.ts
Closes https://github.com/BoltzExchange/boltz-web-app/issues/784
Depends on https://github.com/BoltzExchange/boltz-backend/pull/774
Working demo: https://webapp-git-routing-fees-boltz.vercel.app/?ref=pro&sendAsset=BTC&receiveAsset=LN
E2E test is gonna start working once the backend PR is merged
=> feat: show routing fees

e2e/refund/refundFile.spec.ts
Closes #525
Only does Chromium on desktop and mobile. But that should be fine
=> test: E2E for refund files

src/components/CreateButton.tsx, src/components/Fees.tsx, src/context/Global.tsx, src/i18n/i18n.ts
Closes #673
Translations need a sanity check
=> feat: adjust network fee when RIF is needed

e2e/boltzClient.ts, e2e/refund/existingRescueFile.json, e2e/refund/rescueFile.spec.ts, package-lock.json, package.json, src/components/CreateButton.tsx, src/context/Global.tsx, src/index.tsx, src/pages/Backup.tsx, src/pages/BackupVerify.tsx, src/pages/Create.tsx
=> Defer swap creation until backup is done

CHANGELOG.md, e2e/refund/rescueFile.spec.ts, package-lock.json, package.json, src/components/settings/Logs.tsx, src/components/settings/RescueKey.tsx, src/i18n/i18n.ts, src/pages/Backup.tsx, src/utils/download.ts, tests/components/Logs.spec.tsx
Closes #846
iOS supports downloading files now
=> refactor: remove QR rescue file generation

src/utils/invoice.ts, tests/utils/fetchInvoice.spec.ts
Closes https://github.com/BoltzExchange/boltz-web-app/issues/859
=> fix: conditionally set amount query param for LN address fetch

src/components/RefundButton.tsx, src/utils/refund.ts
=> feat: Refund all UTXOs in one transaction

src/components/CreateButton.tsx
First resolve reliably takes up to 18 seconds for me. Thereafter it's much faster...
=> chore: bump lnurl & bolt12 resolve timeout to 25 seconds

src/pages/Pay.tsx, src/style/index.scss
=> fix: Settings icon overlap on very small screens

src/components/CreateButton.tsx, src/components/LoadingSpinner.tsx, src/style/loadingSpinner.scss
=> feat: add loading signal to `ButtonCreate`

src/components/CreateButton.tsx, src/utils/promise.ts, tests/utils/promise.spec.ts
To avoid having to wait for both, LNURL and BIP-353, promises to resolve
=> refactor: race invoice timeout

package-lock.json, package.json, src/utils/hardware/TrezorSigner.ts
Fixes `Deriving addresses failed: bad address checksum` for our native Trezor integration
=> fix: address derivation for RSK from Trezor

src/components/CreateButton.tsx, src/pages/Create.tsx, src/status/TransactionClaimed.tsx, src/status/TransactionLockupFailed.tsx, src/style/index.scss, tests/components/CreateButton.spec.tsx, tests/pages/Create.spec.tsx
Closes #749
This PR adds most denominations we were missing and fixes the formatting of existing ones.
Some denominations are still to be added on #313.
=> Add missing denominations

src/pages/Create.tsx
=> fix: revalidate amount on backspace deletion

index.html, src/components/Nav.tsx, src/components/settings/Denomination.tsx, src/index.tsx, src/style/footer.scss, src/style/hero.scss, src/style/index.scss, src/style/legal.scss, src/style/loadingSpinner.scss, src/style/nav.scss, src/style/notification.scss, src/style/pagination.scss, src/style/qrscan.scss, src/style/settings.scss, src/style/swaplist.scss, src/style/tabs.scss, src/style/theme.scss, src/style/tooltip.scss, src/style/vars.scss, src/style/web3.scss
Closes [#790](https://github.com/BoltzExchange/boltz-web-app/issues/790)
=> feat: Add Boltz Pro Theme

e2e/refund/rescueFile.spec.ts, src/components/CopyButton.tsx, src/components/CreateButton.tsx, src/components/InvoiceInput.tsx, src/components/MnemonicInput.tsx, src/i18n/i18n.ts, src/index.tsx, src/pages/Backup.tsx, src/pages/BackupMnemonic.tsx, src/pages/BackupVerifyExisting.tsx, src/pages/MnemonicVerify.tsx, src/pages/RefundExternal.tsx, src/style/index.scss, src/style/nav.scss, src/style/pagination.scss, src/style/tabs.scss, src/style/theme.scss, tests/components/CopyButton.spec.tsx, tests/components/MnemonicInput.spec.tsx, tests/pages/MnemonicVerify.spec.tsx
=> feat: Add option to display mnemonic as alternative to download key file

e2e/urlParams.spec.ts, src/components/MnemonicInput.tsx, src/pages/BackupVerifyExisting.tsx, src/pages/RefundExternal.tsx
=> feat: Use `?mode=rescue-key` param to display mnemonic input
