src/index.jsx

The Breez app links to us, but not to the main page but `/swapbox`: https://github.com/breez/breezmobile/blob/a1b0ffff902dfa2210af8fdb047b715535ff11e9/src/json/vendors.json#L30
This PR shows the swap box on that link

swapbox link for compatibility with breez

---

src/Create.jsx
src/status/SwapCreated.jsx

may fix https://github.com/BoltzExchange/boltz-web-app/issues/229
This implementation should still be compatible with providers that return an object on `enable()` but will also allow WebLN providers that do not return anything when `enable()` is called to reach the call to `makeInvoice` so users can make payments on boltz.exchange even if they are not using the Alby extension
also see https://github.com/getAlby/lightning-browser-extension/issues/2596 for more context on spec considerations

fix: enable() should not expect an object

---

src/Nav.jsx
src/i18n/detect.js
src/i18n/index.js
src/index.jsx
src/signals.js
tests/i18n/detect.spec.js

works for chromium, did not work for firefox for me, navigator.language still returned en-EN despite configure it to german. maybe i did something wrong?
detect the `navigator.language` browser language setting and set the wepapps i18n accordingly.
i18n is only saved into localstorage when manually selected and used from there on.
closes #270

feat: browser language detection

---

src/Pay.jsx
src/components/BlockExplorer.jsx
src/components/ConnectMetamask.jsx
src/components/EthereumTransaction.jsx
src/configs/config.regtest.js
src/i18n/i18n.js
src/status/InvoiceSet.jsx
src/status/TransactionConfirmed.jsx
src/utils/swapChecker.js

It makes no sense to show the contract address for RSK swaps, because every RSK swap uses the same contract address.
So this PR refactors what we show on the block explorer link for RSK swaps, which is either the lockup or claim transaction, whichever is relevant at a given step

refactor: show tx links for RSK

---

src/helper.js

and default to BTC/BTC. this only happens while development, running on the mainnet api which is still missing the new asset beeing worked on.

fix: handle js error when asset is missing on api

---

src/helper.js

fixes: failure reason disappearing on lockup failed status page after a reload

fix: failure reason is overwritten

---

src/Refund.jsx

small little fix, emtpy refund swaplist made a ugly space

fix: empty swaplist on `/refund`

---

package-lock.json

chore: update vite

---

src/components/RefundButton.tsx

The creation of Taproot refund transactions can take a second or two, so we gotta disable the button while the transaction is being created to prevent users from clicking multiple times

fix: disable refund button while transaction is being created

---

src/i18n/i18n.ts
src/pages/Pay.tsx
src/status/InvoiceSet.tsx
src/status/SwapCreated.tsx

add links on SwapCreated and InvoiceSet on the QR code and as button.
its working for alby on browser for me i did not test bip21 yet.
closes #299
i replaced the copy bip21 for the open in wallet button, usually you don't really want to copy bip21 right? else we get a small ui issue because we have to less room to make it look good.

feat: deeplinks for wallets

---

src/pages/Create.tsx

closes #452
we should actually only switch if its >= 10 so you cannot enter 9.x :)

fix: autoswitch off by 1

---

src/components/AddressInput.tsx
src/components/ConnectMetamask.tsx
src/components/CreateButton.tsx
src/components/InvoiceInput.tsx
src/context/Create.tsx
src/context/Global.tsx
src/pages/Create.tsx
tests/helper.tsx
tests/pages/Create.spec.tsx

closes #482
renamed signal `sendAmountValid` into `amountValid` because it counts for both

feat: amount max/min error should have prio

---

index.html

feat: add loading animation

---

src/pages/Create.tsx
src/utils/denomination.ts
tests/pages/Create.spec.tsx
tests/utils/denomination.spec.ts

**Description:**
This PR introduces the satcomma standard for formatting sats amounts. You can read [Bitcoin Magazine's 2021 article](https://bitcoinmagazine.com/culture/satcomma-standard-look-at-bitcoin-this) on the subject if you're not familiar with it.
The satcomma standard promotes readability and clarity when dealing with satoshis, by inserting a separator such as spaces or commas every three digits, starting from the decimal point for BTC values or from the least significant digit for satoshi amounts.
**Reasoning:**
- **User Experience**: Improving the way sats amounts are displayed can enhance the user experience, making it easier for users to verify amounts at a glance without counting digits
- **Standardization** - Satscomma is a standard recommended by …

feat: Implement Satscomma Formatting for Sats Amounts

---

src/i18n/i18n.ts
src/pages/Refund.tsx
tests/pages/Refund.spec.tsx

feat: intermediate step when uploading refundjson and proper error

---

src/i18n/i18n.ts
src/pages/Create.tsx
src/utils/denomination.ts
tests/utils/denomination.spec.ts

closes #305
it pretty though too differentiate between invalid amount  (max) or invalid characters on the regex, can we do 1 error message for all i think it is sufficient?

feat: improve pasting

---

src/pages/Pay.tsx

Right now, invalid config is being thrown when a swap that is not in the history is being accessed

fix: error handling for null swap in pay

---

src/components/AddressInput.tsx
src/components/ConnectMetamask.tsx
src/components/CreateButton.tsx
src/components/InvoiceInput.tsx
src/context/Create.tsx
src/i18n/i18n.ts
src/pages/Create.tsx
tests/components/CreateButton.spec.tsx

- button label is now way easier to work with
- validation only happens if there is a amount set at all

fix: bail validation and refactor create button labels

---

package-lock.json
package.json
src/utils/validation.ts

This PR updates some dependencies, including boltz-core to be able to use the new [`compareTrees`](https://github.com/BoltzExchange/boltz-core/commit/ce129faed3c3914358e5b697a4d1e4d612e711e7) function in v2.1.2

chore: use compareTrees function from boltz-core

---

src/pages/Refund.tsx

happened if status returned a 404, request errors are already logged so do nothing. ps. this should never happen in production :)

bug: catch exception on refund page

---

src/components/CopyButton.tsx
tests/components/CopyButton.spec.tsx

should have spaces in sat amount when copying.
spaces can be safely replaced for all copies, its never valid

bug: remove spaces from copy sat amount

---

package-lock.json
package.json
src/components/CreateButton.tsx
src/components/RefundButton.tsx
src/components/SwapChecker.tsx
src/components/SwapList.tsx
src/context/Global.tsx
src/i18n/i18n.ts
src/pages/History.tsx
src/pages/Pay.tsx
src/pages/Refund.tsx
src/pages/RefundStep.tsx
src/status/InvoiceSet.tsx
src/status/TransactionConfirmed.tsx
src/utils/download.ts
tests/components/RefundButton.spec.tsx
tests/pages/Refund.spec.tsx

closes #498
refactor how to add/update/get a swap via globalContext

fix: multiple tabs localstorage issue

---

src/components/SwapList.tsx
src/style/index.scss
tests/components/SwapList.spec.tsx

Uses `<a>` for the links in the swap history, so that they can be clicked with Ctrl + click and open in a new tab. Useful for when you are searching for a specific swap so just open buncha tabs from your history and scroll through them instead of going back and forth. Should be safe to have lots of tabs open now, that we fixed the race condition.
Also removes an unused property from `SwapList`

refactor: use a for swap history links

---

src/utils/denomination.ts
tests/utils/denomination.spec.ts

Really small numbers, eg 14 sats, got converted to 0.0000001 BTC, which is not correct. This PR changes the way we handle scientific notation when converting to string to fix that

fix: small number BTC denomination

---

src/components/Fees.tsx
src/utils/compat.ts
src/utils/refund.ts
tests/components/AddressInput.spec.tsx
tests/components/Fees.spec.tsx
tests/utils/compat.spec.ts
tests/utils/validation.spec.ts

When sending to an unconfidential address from a confidential input we have to add a confidential OP_RETURN. That OP_RETURN output contains 1 sat (because blinding 0 sats is flaky) which is then missing from the fee.
This PR adds 1 sat to the fee when sending to an unconfidential address.

Allow unconfidential addresses again

---

src/components/SwapChecker.tsx

dont filter swap().id from the swapchecker, createEffect wont work on a reload, because the websockets are not yet initialized when the effect is triggered thus never subscribung to the active swap. also because we use a set here, i think there is no worry of duplicate listeners anyway

fix: retry claiming on pagereload

---

src/components/SwapChecker.tsx

swapchecker was wrongly overwriting the status of the swap status page you were on which lead to wrong error messages

bug: only set failure reason and swap status tx if on current swap

---

src/components/SwapList.tsx
src/i18n/i18n.ts

this makes german translations a one liner again

feat: use trash icon instead of `delete` in SwapList component

---

src/components/DownloadRefund.tsx

Taproot swaps and especially chain swaps save much more data in the refund file. We need to increase the size of the QR code so that it can be scanned properly.

fix: increase refund QR size

---

src/utils/claim.ts

For using Musig, we need the WASM version of secp-zkp to be initialized. That was not the case on page reload because the function that constructs claim transactions was not calling the initializer of secp-zkp.

fix: initialize secp before creating claim transaction

---

Dockerfile
nginx.conf

`try_files $uri /index.html =404;` tells Nginx to always serve the `index.html` instead of the default 404 page, when a path that is not `index.html` is accessed.
This is needed so that our router in the web app works on refreshes.

fix: Nginx 404 with Docker on paths

---

src/utils/logs.ts

after trying to reproduce #602 i found that it already was fixed, but there was still an issue where the errormessage wasn't found in the logs. issue was `typeof Error` return `object` so the logger treated is as object and tried to JSON.stringify it. that made it to display just `{}`

fix: error message was swallowed by JSON.stringify

---

src/config.ts
src/i18n/i18n.ts
src/pages/Hero.tsx

- node*s* (plural)
- remove link in the headline, with public explorers it can only link to one node and it was broken on testnet

fix: Lightning Nodes i18, remove link from headline

---

tests/components/PayOnchain.spec.tsx

not sure why but separator was set to `,` and expected a `.` in the test

fix: test payonchain separator was `,`

---

src/components/QrScan.tsx
src/i18n/i18n.ts

closes #600
@kilrau translations

fix: error on camera permissions denied

---

.prettierrc
docs/README.md
docs/pwa.md
docs/urlParams.md
e2e/submarineSwap.spec.ts
e2e/urlParams.spec.ts
e2e/utils.ts
src/consts/Assets.ts
src/context/Create.tsx
src/context/Global.tsx
src/utils/urlParams.ts

closes #334
adds invoice, address, asset, sendAmount, receiveAmount

feat: improve embedding of swapbox

---

e2e/bolt12.spec.ts
e2e/utils.ts
jest.config.js
package-lock.json
package.json
src/components/CreateButton.tsx
src/components/InvoiceInput.tsx
src/config.ts
src/context/Create.tsx
src/i18n/i18n.ts
src/utils/boltzClient.ts
src/utils/invoice.ts
vite.config.mjs

Closes https://github.com/BoltzExchange/boltz-web-app/issues/669
Depends on https://github.com/BoltzExchange/boltz-backend/pull/664

feat: bolt12 support for submarine swaps

---

src/context/Web3.tsx

Closes #696
Not sure yet if we want to do this though. The `window.ethereum` is flaky when you have multiple browser wallets installed and by the wallet not supporting [EIP-6963](https://eips.ethereum.org/EIPS/eip-6963), it could not support other standards we need (eg signed typed data) either.
~Maybe only show the `window.ethereum` wallet if no others are found?~
The "Browser native" provider will only be shown when there are no EIP-6963 providers available

feat: browser native web3 wallet support

---

src/components/BlockExplorerLink.tsx
src/components/LockupEvm.tsx
src/components/SwapChecker.tsx

Closes #692
The transaction button is not hidden on the continue page. Felt weird to hide. Wdyt @kilrau?

feat: show EVM lockup transactions

---

e2e/submarineSwap.spec.ts
src/config.ts
src/i18n/i18n.ts
src/status/TransactionClaimed.tsx

Closes #746 
@kilrau I am not sure about wording and it's missing translations

feat: validate-payment.com instead of copy preimage

---

src/components/ContractTransaction.tsx
src/components/RefundButton.tsx
src/i18n/i18n.ts
src/pages/Refund.tsx
src/pages/RefundEvm.tsx

refactor: nicer screen for logs refunds

---

e2e/evm/noBrowserWallet.spec.ts
src/components/ConnectWallet.tsx
src/components/CreateButton.tsx
src/context/Web3.tsx
src/utils/helper.ts

Closes #758 
https://github.com/user-attachments/assets/02fb5094-a321-475e-933a-11157dc259c8

fix: no refund file download in mobile EVM browser

---

src/context/Web3.tsx

The provider expects the chain ID in hex format

fix: web3 add chain prompt

---

src/consts/LocalStorage.ts
src/context/Global.tsx
src/utils/helper.ts

Needed for a future update which allows fees to change based on the referral id. To show those changed fees, we need to tell the API our referral id in requests that fetch the pairs; easiest way is to just pass the id in every request header

chore: pass referral id in every request header

---

src/components/CreateButton.tsx

fix: refund files for non RBTC pairs in mobile EVM browsers

---

src/components/RefundButton.tsx
src/pages/RefundExternal.tsx

refactor: refund address input

---

src/pages/Create.tsx

Send and receive amounts autocomplete interferes with asset selection in mobile browsers:
This PR removes them.

chore: disable amounts input autocomplete

---

src/components/AssetSelect.tsx
src/components/Reverse.tsx
tests/components/AssetSelect.spec.tsx
tests/components/Reverse.spec.tsx

Closes #751
Closes #754
- Address input is now cleared when switching directions.
- Invalid addresses are not cleared when switching directions.

Clean address input on direction switch

---

src/pages/Pay.tsx
src/style/index.scss

chore: make swap not found page look nicer

---

src/i18n/i18n.ts
src/utils/boltzClient.ts
src/utils/helper.ts

refactor: cleanup external broadcast

---

src/components/settings/Denomination.tsx
src/style/index.scss
tests/components/Denomination.spec.tsx

Add labels to denomination buttons as a way of increasing clarity on the meaning of each symbol.
Aligned items on center to prevent elements from overlapping on small screens

Add labels to denomination buttons

---

src/pages/Refund.tsx

Closes #806
I have tested this by creating a few swaps and:
- letting them expire without paying (these were not displayed);
- paying them after they've expired (these were displayed);
- paying an incorrect amount (these were displayed);

fix: Don't show swaps as 'refundable' when there was no lockup tx

---

src/i18n/i18n.ts

Updating https://beta.boltz.exchange/refund/external wording with "rescue key":
* `invalid_refund_file:`
* `refund_a_swap_subline:`
* `refund_external_explainer:`
and some other minor fixes en `de` and `es`.

feat: external refund rescue key wording

---

src/pages/Pay.tsx
src/style/index.scss
tests/pages/Pay.spec.tsx

Closes #813 
Also added the `RefundButton` for a swap with the state `swap.waitingForRefund`:

Chain Swaps: Rename transaction.refunded state in Web App

---

src/components/CreateButton.tsx
src/context/Create.tsx
src/utils/invoice.ts

This PR adds a function `isLightningAddress` to more accurately determine if we should handle a given `destination` as eligible for parsing the `sendAmount` query parameter.
Previously the logic dictated that any `LN` type destination should defer to the invoice's embedded amount -- but this did not work for LN addresses.

fix: parse query params when destination is an LN address

---

e2e/refund/refund.spec.ts
e2e/refund/rescueFile.spec.ts
e2e/utils.ts
src/components/LoadingSpinner.tsx
src/components/SwapList.tsx

Closes #856
Refunding multiple UTXOs on the following scenarios:
`transaction.lockupFailed`: has 1 UTXO known by both Boltz and the block explorer, and 2 known only by the block explorer (3 total).
`invoice.failedToPay`: has both UTXOs known only by the block explorer.

test: Add e2e tests for refunding multiple UTXOs

---

build.py
build_dnssec_prover.py

Rather than require python3 be installed exactly at /bin/python3

Get python3 location from env in shebang

---

src/pages/History.tsx
src/utils/rescueFile.ts
tests/pages/History.spec.tsx
tests/utils/rescueFile.spec.ts

Closes #867
Rescue key should be included on backup of multiple swaps (Backup button on `History` page), so that users can refund these swaps later on, if needed.
Old refund files don't need to include the mnemonic since they use `refundPrivateKey` for the refunds.

feat: Export rescue key in backup

---

src/context/Create.tsx
tests/context/Create.spec.tsx

Closes #884
The problem occurred when`setDestination` returned `destinationAsset` as `null`, but the `if` checked if `destinationAsset` was `undefined`.
https://github.com/BoltzExchange/boltz-web-app/blob/cb62f517c97cf35e798922b79feaa8900cd88f16/src/context/Create.tsx#L88-L100
Fixed by returning `destinationAsset` as `undefined` (instead of redefining it as `null`) and added unit tests covering this scenario.

fix: urlParam `receiveAsset` not working

---

eslint.config.mjs
src/components/CopyBox.tsx
src/components/CopyButton.tsx
src/components/PayInvoice.tsx
src/components/PayOnchain.tsx
src/consts/CopyContent.ts
src/style/index.scss
src/utils/compat.ts
tests/components/CopyBox.spec.tsx

Closes #875
The issue was about adding a "copy on click" functionality to the address/invoice "input", however the functionality was already there, it just wasn't clear due to lack of clues about it.
This PR adds to the "input" the same icon aspect & behavior we already had in other buttons:

feat: improve UX for copying address/invoice on click

---

src/components/Nav.tsx

moved "help" one position to the left to have it even more visible

chore: reorder header menu

---

src/components/SwapChecker.tsx
src/i18n/i18n.ts
src/pages/Pay.tsx
src/status/TransactionMempool.tsx

Closes #815 
Displays generic prompt when user has Reverse or Chain swap pending and is on desktop.
Tested on Tor browser:
Also displays this warning (mobile AND BTC -> x only):

feat: prompt on tab close with pending swaps

---

src/components/CreateButton.tsx
src/components/InvoiceInput.tsx
tests/components/CreateButton.spec.tsx

Closes #686.
In this PR, amounts are now only validated when there are no invoice errors.

fix: properly handle zero-amount invoice error
